before:
  hooks:
    - go mod tidy

builds:
- id: "build-with-completions"
  binary: idseq
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  ldflags: &ldflags
    - -s -w
    - -X github.com/chanzuckerberg/idseq-cli-v2/pkg.Version={{.Version}}
    - -X github.com/chanzuckerberg/idseq-cli-v2/pkg/auth0.defaultClientID={{.Env.AUTH_0_CLIENT_ID}}
    - -X github.com/chanzuckerberg/idseq-cli-v2/pkg/auth0.defaultAuth0Host={{.Env.AUTH0_HOST}}
    - -X github.com/chanzuckerberg/idseq-cli-v2/pkg/idseq.defaultIDSeqBaseURL={{.Env.IDSEQ_BASE_URL}}
  hooks:
    post: "scripts/generate_completions.sh {{.Path}}"
- binary: idseq
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  ignore:
    - goos: linux
      goarch: amd64
  ldflags: *ldflags

release:
  prerelease: true

archives:
  - files:
    - LICENSE.md
    - README.md
    - bash_completion
    - zsh_completion
    - fish_completion
    - powershell_completion

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{.Tag}}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
