before:
  hooks:
    - go mod tidy

builds:
- id: "build-with-completions"
  binary: czid
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  ldflags: &ldflags
    - -s -w
    - -X github.com/chanzuckerberg/idseq-cli-v2/pkg.Version={{.Version}}
    - -X github.com/chanzuckerberg/idseq-cli-v2/pkg/auth0.defaultClientID={{.Env.AUTH_0_CLIENT_ID}}
    - -X github.com/chanzuckerberg/idseq-cli-v2/pkg/auth0.defaultAuth0Host={{.Env.AUTH0_HOST}}
    - -X github.com/chanzuckerberg/idseq-cli-v2/pkg/czid.defaultCZIDBaseURL={{.Env.CZID_BASE_URL}}
  hooks:
    post: "scripts/generate_completions.sh {{.Path}}"
- binary: czid
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  ignore:
    - goos: linux
      goarch: amd64
  ldflags: *ldflags

release:
  prerelease: true

archives:
  # Default without version for easy latest release linking
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}{{if .Mips}}_{{.Mips}}{{end}}"
    wrap_in_directory: true
    format_overrides:
    - goos: windows
      format: zip
    files:
    - LICENSE.md
    - README.md
    - bash_completion
    - zsh_completion
    - fish_completion
    - powershell_completion
  

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{.Tag}}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
