before:
  hooks:
    - go mod tidy

builds:
- binary: idseq
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/chanzuckerberg/idseq-cli-v2/pkg.Version={{.Version}}

release:
  prerelease: true

archives:
  - files:
    - LICENSE.md
    - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
