name: Check
on:
  push:
  release:
    types:
      - created
jobs:
  Build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.5
      - uses: actions/checkout@v2
      - name: Deps
        run: make deps
      - name: Build
        run: make build
  Test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.5
      - uses: actions/checkout@v2
      - name: Deps
        run: make deps
      - name: Test
        run: |
          make test 
          bash <(curl -s https://codecov.io/bash)
  Dependencies:
    name: Dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.5
      - uses: actions/checkout@v2
      - name: Deps
        run: make deps
      - name: Dependencies
        run: make check-mod
  Lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
  Prerelease:
    name: Prerelease
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: goreleaser/goreleaser-action@v2
        if: ${{ github.event_name == "release" && github.event.release.prerelease }}
        with:
          version: latest
          args: release --rm-dist -f .goreleaser.prerelease.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
