name: Check
on:
  push:
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.5
      - uses: actions/checkout@v2
      - name: Deps
        run: make deps
      - name: Build
        run: make build
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.5
      - uses: actions/checkout@v2
      - name: Deps
        run: make deps
      - name: Test
        run: |
          make test 
          bash <(curl -s https://codecov.io/bash)
  Dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.5
      - uses: actions/checkout@v2
      - name: Deps
        run: make deps
      - name: Dependencies
        run: make check-mod
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.29
