name: CICD

on:
  push:
  release:
    types:
      - created

env:
  GO_VERSION: 1.16.3

jobs:
  Build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - name: Deps
        run: make deps
      - name: Build
        run: make build
  Test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - name: Deps
        run: make deps
      - name: Test
        run: |
          make test
          bash <(curl -s https://codecov.io/bash)
  Dependencies:
    name: Dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - name: Deps
        run: make deps
      - name: Dependencies
        run: make check-mod
  Lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
  Prerelease:
    name: Prerelease
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'release' && github.event.release.prerelease }}
    needs: [Build, Test, Dependencies, Lint]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist -f .goreleaser.prerelease.yml
        env:
          AUTH_0_CLIENT_ID: ${{ secrets.AUTH_0_CLIENT_ID }}
          AUTH0_HOST: ${{ secrets.AUTH0_HOST }}
          IDSEQ_BASE_URL: ${{ secrets.IDSEQ_BASE_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Release:
    name: Release
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'release' && !github.event.release.prerelease }}
    needs: [Build, Test, Dependencies, Lint]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist -f .goreleaser.yml
        env:
          AUTH_0_CLIENT_ID: ${{ secrets.AUTH_0_CLIENT_ID }}
          AUTH0_HOST: ${{ secrets.AUTH0_HOST }}
          IDSEQ_BASE_URL: ${{ secrets.IDSEQ_BASE_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.CZIBUILDBOT_GITHUB_TOKEN }}
