name: Release
on:
  release:
    types: [created]
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.5
        id: go
      - name: Wait on Checks
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetches everything, for some reason goreleaser needs this
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        if: "!github.event.release.prerelease"
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.CZIBUILDBOT_GITHUB_KEY }}
      - name: Prerelease
        uses: goreleaser/goreleaser-action@v2
        if: "github.event.release.prerelease"
        with:
          version: latest
          args: release --rm-dist -f .goreleaser.prerelease.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
